# Generated by Django 6.0.5 on 2026-05-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="train",
            old_name="carriages_count",
            new_name="carriages",
        ),
    ]
